name: Transcription

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Set up protoc 
        uses: arduino/setup-protoc@v2
        with:
          version: "25.1"
      - name: Install dependencies
        run: npm install -g protoc-gen-ts && make install
      - name: Typecheck 
        run: make type_check
      - name: Test
        run: make test
